[package]
name = "user-services-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }

database-models = { workspace = true }
dependent-models = { workspace = true }
media-models = { workspace = true }
traits = { workspace = true }
user-service = { workspace = true }
