[package]
name = "spotify-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
data-encoding = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }

application-utils = { workspace = true }
cache-service = { workspace = true }
common-models = { workspace = true }
common-utils = { workspace = true }
config-definition = { workspace = true }
database-models = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }
traits = { workspace = true }
