[package]
name = "spotify-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
data-encoding = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

application-utils = { workspace = true }
cache-service = { path = "../../services/cache" }
common-models = { workspace = true }
common-utils = { workspace = true }
config-definition = { workspace = true }
database-models = { path = "../../models/database" }
dependent-models = { path = "../../models/dependent" }
enum-models = { workspace = true }
media-models = { path = "../../models/media" }
supporting-service = { path = "../../services/supporting" }
traits = { path = "../../traits" }
