[package]
name = "audiobookshelf-importer-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
data-encoding = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

application-utils = { workspace = true }
common-utils = { workspace = true }
dependent-entity-utils = { workspace = true }
dependent-models = { workspace = true }
dependent-provider-utils = { workspace = true }
enum-models = { workspace = true }
external-models = { workspace = true }
google-books-provider = { workspace = true }
hardcover-provider = { workspace = true }
importer-models = { workspace = true }
media-models = { workspace = true }
openlibrary-provider = { workspace = true }
supporting-service = { workspace = true }
