services:
  backend-bull-board:
    restart: unless-stopped
    image: venatum/bull-board
    ports:
      - "3002:3000"
    environment:
      REDIS_HOST: backend-redis
    depends_on:
      backend-redis:
        condition: service_healthy

  backend-redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    healthcheck:
      retries: 5
      timeout: 5s
      interval: 2s
      test: ["CMD", "redis-cli", "ping"]

  backend-postgres:
    restart: unless-stopped
    image: postgres:18-alpine
    command: postgres -c shared_preload_libraries=pg_stat_statements -c wal_level=logical
    ports:
      - "5432:5432"
    volumes:
      - backend_postgres_storage:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      retries: 5
      timeout: 5s
      interval: 2s
      test: ["CMD-SHELL", "pg_isready -U postgres"]

  app-backend:
    restart: unless-stopped
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      backend-redis:
        condition: service_healthy
      backend-postgres:
        condition: service_healthy
    environment:
      FRONTEND_URL: http://localhost:8000
      REDIS_URL: redis://backend-redis:6379
      SERVER_ADMIN_ACCESS_TOKEN: super-secret-token-that-should-be-changed
      DATABASE_URL: postgresql://postgres:postgres@backend-postgres:5432/postgres

volumes:
  backend_postgres_storage:
