[package]
name = "providers"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
application-utils = { path = "../utils/application" }
async-trait = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
common-utils = { path = "../utils/common" }
config = { path = "../config" }
const-str = { workspace = true }
convert_case = { workspace = true }
enums = { path = "../enums" }
graphql_client = "=0.14.0"
hashbag = "=0.1.12"
isolang = { version = "=2.4.0", features = ["list_languages"] }
itertools = { workspace = true }
models = { path = "../models" }
paginate = "=1.1.11"
rand = "=0.9.0-alpha.2"
reqwest = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
rust_iso3166 = "=0.1.13"
scraper = "=0.20.0"
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true }
tracing = { workspace = true }
traits = { path = "../traits" }
