[package]
name = "miscellaneous-tracking-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }
tracing = { workspace = true }

common-models = { workspace = true }
media-models = { workspace = true }
miscellaneous-service = { workspace = true }
miscellaneous-calendar-service = { workspace = true }
miscellaneous-progress-service = { workspace = true }
traits = { workspace = true }
