[package]
name = "dependent-entity-list-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }

application-utils = { workspace = true }
cache-service = { workspace = true }
common-models = { workspace = true }
database-models = { workspace = true }
database-utils = { workspace = true }
dependent-models = { workspace = true }
fitness-models = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust_decimal"]
