[package]
name = "statistics-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
async-graphql = { workspace = true }
common-models = { path = "../../models/common" }
statistics-service = { path = "../../services/statistics" }
traits = { path = "../../traits" }
