[package]
name = "importer-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }

database-models = { path = "../../models/database" }
importer-service = { path = "../../services/importer" }
media-models = { path = "../../models/media" }
traits = { path = "../../traits" }
