[package]
name = "watcharr-importer-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

common-models = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
importer-models = { workspace = true }
media-models = { workspace = true }
