[package]
name = "miscellaneous-trending-and-events-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
enum_meta = { workspace = true }
itertools = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }

cache-service = { workspace = true }
database-models = { workspace = true }
dependent-entity-utils = { workspace = true }
dependent-models = { workspace = true }
dependent-notification-utils = { workspace = true }
dependent-provider-utils = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust_decimal"]
