[package]
name = "hevy-importer-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }
indexmap = { workspace = true }
itertools = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
database-models = { workspace = true }
dependent-import-utils = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
fitness-models = { workspace = true }
importer-models = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }
