[package]
name = "collection-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }

collection-service = { path = "../../services/collection" }
common-models = { path = "../../models/common" }
dependent-models = { path = "../../models/dependent" }
media-models = { path = "../../models/media" }
traits = { path = "../../traits" }
