[package]
name = "imdb-importer-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
csv = { workspace = true }
itertools = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }

common-models = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
importer-models = { workspace = true }
media-models = { workspace = true }
tmdb-provider = { workspace = true }
