[package]
name = "dependent-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
apalis = { workspace = true }
application-utils = { path = "../application" }
async-graphql = { workspace = true }
background = { path = "../../background" }
chrono = { workspace = true }
chrono-tz = { workspace = true }
common-models = { path = "../../models/common" }
common-utils = { path = "../common" }
config = { path = "../../config" }
database-models = { path = "../../models/database" }
database-utils = { path = "../database" }
dependent-models = { path = "../../models/dependent" }
enums = { path = "../../enums" }
fitness-models = { path = "../../models/fitness" }
importer-models = { path = "../../models/importer" }
itertools = { workspace = true }
media-models = { path = "../../models/media" }
moka = { workspace = true }
nanoid = { workspace = true }
providers = { path = "../../providers" }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
traits = { path = "../../traits" }
user-models = { path = "../../models/user" }

[package.metadata.cargo-machete]
ignored = ["tracing"]
