[package]
name = "dependent-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
application-utils = { path = "../application" }
async-graphql = { workspace = true }
background-models = { path = "../../models/background" }
chrono = { workspace = true }
common-models = { path = "../../models/common" }
common-utils = { path = "../common" }
config = { path = "../../config" }
database-models = { path = "../../models/database" }
database-utils = { path = "../database" }
dependent-models = { path = "../../models/dependent" }
enum-models = { path = "../../models/enum" }
enum_meta = { workspace = true }
fitness-models = { path = "../../models/fitness" }
futures = { workspace = true }
importer-models = { path = "../../models/importer" }
itertools = { workspace = true }
markdown = { workspace = true }
media-models = { path = "../../models/media" }
migrations = { path = "../../migrations" }
nanoid = { workspace = true }
notification-service = { path = "../../services/notification" }
providers = { path = "../../providers" }
rand = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
sea-orm = { workspace = true }
sea-query = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
slug = { workspace = true }
sqlx = { workspace = true }
supporting-service = { path = "../../services/supporting" }
tracing = { workspace = true }
traits = { path = "../../traits" }
user-models = { path = "../../models/user" }
uuid = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["serde_json", "sqlx", "tracing"]
