[package]
name = "miscellaneous-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }
uuid = { workspace = true }

common-models = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
miscellaneous-service = { path = "../../services/miscellaneous" }
traits = { workspace = true }
