[package]
name = "netflix-importer-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
indexmap = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
zip = { workspace = true }

common-models = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
importer-models = { workspace = true }
media-models = { workspace = true }
miscellaneous-lookup-service = { workspace = true }
supporting-service = { workspace = true }
