[package]
name = "router-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-graphql = { workspace = true }
axum = { workspace = true }
nanoid = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

common-utils = { workspace = true }
config-definition = { workspace = true }
integration-service = { path = "../../services/integration" }

[package.metadata.cargo-machete]
ignored = ["tracing"]
