[package]
name = "router-resolver"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
async-graphql = { workspace = true }
axum = { workspace = true }
common-utils = { path = "../../utils/common" }
config = { path = "../../config" }
integration-service = { path = "../../services/integration" }
nanoid = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["tracing"]
