[package]
name = "router-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-graphql = { workspace = true }
axum = { workspace = true }
nanoid = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

background-models = { workspace = true }
cache-service = { workspace = true }
common-utils = { workspace = true }
config-definition = { workspace = true }
dependent-models = { workspace = true }
supporting-service = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["tracing"]
