[package]
name = "myanimelist-importer-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
flate2 = { workspace = true }
itertools = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde-xml-rs = { workspace = true }

common-utils = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
