[package]
name = "user-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }

common-models = { path = "../../models/common" }
database-models = { path = "../../models/database" }
dependent-models = { path = "../../models/dependent" }
media-models = { path = "../../models/media" }
traits = { path = "../../traits" }
user-models = { path = "../../models/user" }
user-service = { path = "../../services/user" }
