[package]
name = "generic-json-importer-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

dependent-models = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["tracing"]
