[package]
name = "common-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
compile-time = "=0.2.0"
const-str = { workspace = true }
dotenvy_macro = { workspace = true }
env-utils = { path = "../env" }
reqwest = { workspace = true }
