[package]
name = "common-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
compile-time = { workspace = true }
const-str = { workspace = true }
enum-models = { path = "../../models/enum" }
env-utils = { path = "../env" }
reqwest = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
