[package]
name = "miscellaneous-entity-user-details-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }

application-utils = { workspace = true }
cache-service = { workspace = true }
common-models = { workspace = true }
database-models = { workspace = true }
database-utils = { workspace = true }
dependent-core-utils = { workspace = true }
dependent-entity-utils = { workspace = true }
dependent-models = { workspace = true }
dependent-seen-utils = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust_decimal", "tracing"]
