[package]
name = "application-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
openidconnect = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }

common-utils = { path = "../common" }
config = { path = "../../config" }
media-models = { path = "../../models/media" }
session-service = { path = "../../services/session" }

[package.metadata.cargo-machete]
ignored = ["tracing"]
