[package]
name = "dependent-details-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }

cache-service = { workspace = true }
common-models = { workspace = true }
dependent-entity-utils = { workspace = true }
database-models = { workspace = true }
database-utils = { workspace = true }
dependent-models = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust_decimal"]
