[package]
name = "traits"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
application-utils = { path = "../utils/application" }
dependent-models = { path = "../models/dependent" }
async-graphql = { workspace = true }
async-trait = { workspace = true }
common-models = { path = "../models/common" }
common-utils = { path = "../utils/common" }
database-models = { path = "../models/database" }
database-utils = { path = "../utils/database" }
media-models = { path = "../models/media" }
supporting-service = { path = "../services/supporting" }
tracing = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["tracing"]
