[package]
name = "dependent-provider-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
rust_decimal = { workspace = true }

anilist-provider = { workspace = true }
audible-provider = { workspace = true }
config-definition = { workspace = true }
enum-models = { workspace = true }
giant-bomb-provider = { workspace = true }
google-books-provider = { workspace = true }
hardcover-provider = { workspace = true }
igdb-provider = { workspace = true }
itunes-provider = { workspace = true }
listennotes-provider = { workspace = true }
manga-updates-provider = { workspace = true }
media-models = { workspace = true }
myanimelist-provider = { workspace = true }
openlibrary-provider = { workspace = true }
spotify-provider = { workspace = true }
supporting-service = { workspace = true }
traits = { workspace = true }
tmdb-provider = { workspace = true }
tvdb-provider = { workspace = true }
vndb-provider = { workspace = true }
youtube-music-provider = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust_decimal"]
