[package]
name = "exporter-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }

common-models = { workspace = true }
exporter-service = { path = "../../services/exporter" }
traits = { path = "../../traits" }
