[package]
name = "mediatracker-importer-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
tracing = { workspace = true }

common-models = { workspace = true }
common-utils = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
importer-models = { workspace = true }
media-models = { workspace = true }
openlibrary-provider = { workspace = true }
