[package]
name = "miscellaneous-search-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }

common-models = { workspace = true }
dependent-models = { workspace = true }
media-models = { workspace = true }
miscellaneous-lookup-service = { workspace = true }
miscellaneous-search-service = { workspace = true }
miscellaneous-trending-and-events-service = { workspace = true }
traits = { workspace = true }
