[package]
name = "miscellaneous-grouping-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }

common-models = { workspace = true }
dependent-models = { workspace = true }
dependent-details-utils = { workspace = true }
dependent-entity-list-utils = { workspace = true }
media-models = { workspace = true }
miscellaneous-entity-user-details-service = { workspace = true }
traits = { workspace = true }
