[package]
name = "fitness-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }
sea-orm = { workspace = true }

database-models = { path = "../../models/database" }
dependent-models = { workspace = true }
fitness-models = { path = "../../models/fitness" }
fitness-service = { path = "../../services/fitness" }
traits = { path = "../../traits" }
