[package]
name = "file-storage-resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { workspace = true }

common-models = { workspace = true }
file-storage-service = { path = "../../services/file-storage" }
media-models = { path = "../../models/media" }
