[package]
name = "miscellaneous-filter-preset-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
nanoid = { workspace = true }
sea-orm = { workspace = true }

cache-service = { workspace = true }
common-models = { workspace = true }
database-models = { workspace = true }
dependent-models = { workspace = true }
dependent-utility-utils = { workspace = true }
supporting-service = { workspace = true }
