[package]
name = "miscellaneous-lookup-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
regex = { workspace = true }
rust_decimal = { workspace = true }
tracing = { workspace = true }

cache-service = { workspace = true }
common-models = { workspace = true }
common-utils = { workspace = true }
dependent-models = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }
tmdb-provider = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust_decimal", "tracing"]
