[package]
name = "miscellaneous-review-service"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
nanoid = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }

common-models = { workspace = true }
database-models = { workspace = true }
database-utils = { workspace = true }
dependent-utility-utils = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust_decimal"]
