[package]
name = "dependent-progress-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }         # TEMP(1611): remove once duplicate seen debug logging is no longer needed

background-models = { workspace = true }
cache-service = { workspace = true }
common-models = { workspace = true }
database-models = { workspace = true }
dependent-details-utils = { workspace = true }
dependent-models = { workspace = true }
dependent-seen-utils = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
supporting-service = { workspace = true }
