[package]
name = "background-models"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
media-models = { path = "../media" }
serde = { workspace = true }
strum = { workspace = true }
uuid = { workspace = true }
