[package]
name = "background-models"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
uuid = { workspace = true }

common-models = { workspace = true }
media-models = { path = "../media" }
