[package]
name = "listennotes-provider"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
itertools = { workspace = true }
reqwest = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }

application-utils = { workspace = true }
cache-service = { path = "../../services/cache" }
common-models = { workspace = true }
common-utils = { workspace = true }
dependent-models = { path = "../../models/dependent" }
enum-models = { workspace = true }
media-models = { path = "../../models/media" }
supporting-service = { path = "../../services/supporting" }
traits = { path = "../../traits" }
