[package]
name = "dependent-notification-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
itertools = { workspace = true }
rust_decimal = { workspace = true }
sea-orm = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

common-models = { workspace = true }
common-utils = { workspace = true }
database-models = { workspace = true }
dependent-entity-utils = { workspace = true }
enum-models = { workspace = true }
media-models = { workspace = true }
notification-service = { workspace = true }
supporting-service = { workspace = true }
traits = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["rust_decimal", "tracing"]
